#!/bin/sh

. ../common.sh

init

compile_cxx foo.C
link foo foo.o

subtest 1
./foo 1
run_gcov foo.C
run_tggcov foo.C
compare_lines foo.C

subtest 2
./foo 2
run_gcov foo.C
run_tggcov foo.C
compare_lines foo.C

subtest 3
./foo 3
run_gcov foo.C
run_tggcov foo.C
compare_lines foo.C

subtest 42
./foo 42
run_gcov foo.C
run_tggcov foo.C
compare_lines foo.C

subtest -1
./foo -1
run_gcov foo.C
run_tggcov foo.C
compare_lines foo.C

