#!/bin/sh

TESTS=
SUPPRESS=
GIVEN=no
LOGFILE=log.`./platform.sh`.`date +%Y%m%dT%H%M%S`

usage ()
{
    echo "Usage: runtest [test...]"
    exit 1
}

istest ()
{
    test -d "$1" -a -f "$1/runtest" -a -x "$1/runtest"
}

addtest ()
{
    GIVEN=yes
    if istest $1 ; then
    	TESTS="$TESTS $1"
    else
    	echo "$0: warning: no such test \"$1\""
    fi
}

issuppressed ()
{
    local t

    for t in $SUPPRESS ; do
    	[ $t = $1 ] && return 0
    done
    return 1
}

addsuppress ()
{
    if istest $1 ; then
    	SUPPRESS="$SUPPRESS $1"
    else
    	echo "$0: warning: no such test \"$1\""
    fi
}

while [ $# -gt 0 ] ; do
    case "$1" in
    test???)
    	addtest $1
	;;
    [0-9]|[0-9][0-9]|[0-9][0-9][0-9])
    	addtest test`printf %03d $1`
	;;
    \!test???)
    	addsuppress ${1#!}
	;;
    \![0-9]|\![0-9][0-9]|\![0-9][0-9][0-9])
    	addsuppress test`printf %03d ${1#!}`
	;;
    -*)
    	usage
	;;
    esac
    shift
done

if [ $GIVEN = no ] ; then
    TESTS=`ls test[0-9][0-9][0-9]/runtest 2>/dev/null | sed -e 's|/runtest||g'`
fi

T2=
for t in $TESTS ; do
    issuppressed $t || T2="$T2 $t"
done
TESTS="$T2"

# echo TESTS=\"$TESTS\"
# exit 1

echo "Running tests, logfile is $LOGFILE"
rm -f $LOGFILE

NRUN=0
NPASS=0
for t in $TESTS ; do
    echo -n $t
    (
	echo "================================================================================"
	echo "==== $t"
    	cd $t
	./runtest
    ) >> $LOGFILE 2>&1
    if [ $? = 0 ]; then
	echo " PASS"
	NPASS=`expr $NPASS + 1`
    else
	echo " FAIL"
    fi
    NRUN=`expr $NRUN + 1`
done

echo "Total: $NPASS/$NRUN tests passed"
