#!/usr/bin/env bash
#
# ggcov - A GTK frontend for exploring gcov coverage data
# Copyright (c) 2004 Greg Banks <gnb@alphalink.com.au>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# $Id: runtest,v 1.5 2005-03-14 07:49:16 gnb Exp $
#

TESTS=
SUPPRESS=
GIVEN=no
PLATFORM=`./platform.sh`
DATE=`date +%Y%m%dT%H%M%S`
LOGFILE=log.$PLATFORM.$DATE

usage ()
{
    echo "Usage: runtest [test...]"
    exit 1
}

istest ()
{
    test -d "$1" -a -f "$1/runtest" -a -x "$1/runtest"
}

addtest ()
{
    GIVEN=yes
    if istest $1 ; then
    	TESTS="$TESTS $1"
    else
    	echo "$0: warning: no such test \"$1\""
    fi
}

issuppressed ()
{
    local t

    for t in $SUPPRESS ; do
    	[ $t = $1 ] && return 0
    done
    return 1
}

addsuppress ()
{
    if istest $1 ; then
    	SUPPRESS="$SUPPRESS $1"
    else
    	echo "$0: warning: no such test \"$1\""
    fi
}

while [ $# -gt 0 ] ; do
    case "$1" in
    test???)
    	addtest $1
	;;
    [0-9]|[0-9][0-9]|[0-9][0-9][0-9])
    	addtest test`printf %03d $1`
	;;
    \!test???)
    	addsuppress ${1#!}
	;;
    \![0-9]|\![0-9][0-9]|\![0-9][0-9][0-9])
    	addsuppress test`printf %03d ${1#!}`
	;;
    -*)
    	echo "Unknown option \"$1\""
    	usage
	;;
    *)
    	usage
	;;
    esac
    shift
done

if [ $GIVEN = no ] ; then
    TESTS=`ls test[0-9][0-9][0-9]/runtest 2>/dev/null | sed -e 's|/runtest||g'`
fi

T2=
for t in $TESTS ; do
    issuppressed $t || T2="$T2 $t"
done
TESTS="$T2"

# echo TESTS=\"$TESTS\"
# exit 1

echo "Running tests, logfile is $LOGFILE"
(
    echo "hostname: \"`hostname`\""
    echo "date: \"$DATE\""
    echo "uname -s: \"`uname -s`\""
    echo "uname -m: \"`uname -m`\""
    echo "uname -r: \"`uname -r`\""
    for f in /etc/*-release _dummy ; do
        [ $f = _dummy ] || echo "head -1 $f: \"`head -1 $f 2>/dev/null`\""
    done
    echo "platform: \"$PLATFORM\""
) > $LOGFILE

NRUN=0
NPASS=0
for t in $TESTS ; do
    echo -n $t
    (
	echo "================================================================================"
	echo "==== $t start"
    	cd $t
	./runtest
    ) >> $LOGFILE 2>&1
    if [ $? = 0 ]; then
	RESULT=PASS
	NPASS=`expr $NPASS + 1`
    else
	RESULT=FAIL
    fi
    echo " $RESULT"
    echo "==== $t $RESULT" >> $LOGFILE
    NRUN=`expr $NRUN + 1`
done

echo "Total: $NPASS/$NRUN tests passed"
