#!/usr/bin/env bash

ENABLE_DB_FLAG=1
. ../common.sh

init "parsing debug RTL dump from gcc -db for callgraph"

compile_c foo.c
link foo foo.o

run foo 1
run foo 2
run foo 23 423

subtest 1
run_gcov foo.c
run_tggcov foo.c
compare_lines foo.c

subtest 2
tggcov_flags -P
run_tggcov foo.c
compare_callgraph
