#!/usr/bin/env bash

. ../common.sh

init "suppression of lines by magical comment"

compile_c foo.c
link foo foo.o

run foo 1
run foo 2
run foo 23 423

subtest 1
run_tggcov -N foo.c
compare_file foo.c

subtest 2
run_tggcov -Y BAZ -Z FOO,BAR -N foo.c
compare_file foo.c

