/*
 * ggcov - A GTK frontend for exploring gcov coverage data
 * Copyright (c) 2001-2003 Greg Banks <gnb@alphalink.com.au>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef _config_h_
#define _config_h_ 1

/*
 * $Id: acconfig.h,v 1.4 2003-06-12 16:59:41 gnb Exp $
 */
 
/*
 * Define as non-zero to turn on debugging prints.
 */
#ifndef DEBUG 
#define DEBUG 0
#endif

/*
 * The fake flag used to be present in the .bbg file format, but
 * disappeared sometime before gcc 2.96.  It was always redundant
 * information, but convenient.  On the bright side, we don't need
 * to cross-check it anymore.
 */
#undef HAVE_BBG_FAKE_FLAG

/*
 * The function gtk_text_buffer_select_range may or may not be
 * present in the gtk2 libraries, we have to work around it if not.
 */
#undef HAVE_GTK_TEXT_BUFFER_SELECT_RANGE

/* The lines below this are generated by autoheader */
/*@TOP@*/

#if 0
#define PACKAGE "foo"
#define VERSION "bar"
#endif

/*@BOTTOM@*/
#endif /* _config_h_ */
