#!/bin/sh

set `sed -n -e 's|^AM_INIT_AUTOMAKE(\([^,]\+\),\([^)]\+\))|\1 \2|p' < configure.in`
PACKAGE=$1
VERSION=$2

SPECFILE=${PACKAGE}.spec
TARBALL=${PACKAGE}-${VERSION}.tar.gz
RPMDIR=rpm.d

#echo PACKAGE=$PACKAGE
#echo VERSION=$VERSION
#echo TARBALL=$TARBALL
#echo RPMDIR=$RPMDIR
#exit 1

set -x

if [ ! -f $SPECFILE ]; then
    autoconf
    autoheader
    automake -a
    ./configure
    if [ ! -f $SPECFILE ]; then
    	echo "Can't build $SPECFILE, giving up"
	exit 1
    fi
fi

if [ ! -f $TARBALL ]; then
    make dist
    if [ ! -f $TARBALL ]; then
    	echo "Can't build $TARBALL, giving up"
	exit 1
    fi
fi

/bin/rm -rf $RPMDIR
mkdir -p $RPMDIR
(cd $RPMDIR ; mkdir -p BUILD RPMS/i386 RPMS/`uname -m` SPECS SRPMS )

rpm -bb \
    --define "_topdir $PWD/$RPMDIR" \
    --define "_sourcedir $PWD" \
    --verbose \
    $SPECFILE

mv -f $(find $RPMDIR/RPMS -type f -name \*.rpm) .
