#!/usr/bin/env bash

. ../common.sh

[ $CALLTREE_ENABLED = yes ] || skip "requires calltree support"

init "Suppression of assert() failure blocks"

compile_c foo.c
link foo foo.o

run foo 1 2

run_gcov foo.c
run_tggcov -S foo.c
compare_status foo.c
