#!/usr/bin/env bash

. ../common.sh

init

compile_cxx foo.C
link foo foo.o

run foo 1
run foo 2
run foo 3
run foo 42
run foo 5

run_gcov foo.C
run_tggcov foo.C
compare_lines foo.C
compare_lines odd.h
compare_lines even.h

