#!/usr/bin/env bash

. ../common.sh

init

compile_cxx foo.C
link foo foo.o

vncdo ./foo 1
vncdo ./foo 2
vncdo ./foo 3
vncdo ./foo 42
vncdo ./foo 5

run_gcov foo.C
run_tggcov foo.C
compare_lines foo.C

