#!/usr/bin/env bash

. ../common.sh

init "nonlocal flow control using C setjmp/longjmp"

compile_c foo.c
link foo foo.o

run foo 1
run foo 2
run foo 3
run foo 4

run_tggcov -N foo.c
compare_file foo.c
