#!/bin/sh

. ../common.sh

init

compile_c foo.c
link foo foo.o

subtest 0
./foo 0
run_gcov foo.c
run_tggcov foo.c
compare_lines foo.c

subtest 1
./foo 1
run_gcov foo.c
run_tggcov foo.c
compare_lines foo.c

subtest 3
./foo 3
run_gcov foo.c
run_tggcov foo.c
compare_lines foo.c

subtest 10
./foo 10
run_gcov foo.c
run_tggcov foo.c
compare_lines foo.c
