#!/usr/bin/env bash

. ../common.sh

CLEAN_FILES="$CLEAN_FILES *f.c *m.c"
init

SUBTESTS="$@"
if [ -z "$SUBTESTS" ] ; then
    SUBTESTS=$(ls *.graph | sed -e 's|^.*/\(.*\)\.graph$|\1|')
fi

for st in $SUBTESTS ; do
    subtest $st
    $srcdir/graphgen.pl $srcdir/$st.graph $srcdir/${st}f.c $srcdir/${st}m.c || continue
    compile_c ${st}f.c
    compile_c ${st}m.c
    link $st ${st}f.o ${st}m.o
    run $st
    run_gcov ${st}f.c
    run_tggcov ${st}f.c
    compare_lines ${st}f.c
done

