#!/usr/bin/env bash

. ../common.sh

CLEAN_FILES="$CLEAN_FILES *f.c *m.c"
init "callgraph diagram layout"

SUBTESTS="$@"
if [ -z "$SUBTESTS" ] ; then
    SUBTESTS=$(ls $srcdir/*.graph | sed -e 's|^.*/\(.*\)\.graph$|\1|')
fi

for st in $SUBTESTS ; do
    subtest $st
    perl $(_srcfile graphgen.pl) $(_srcfile $st.graph) ${st}f.c ${st}m.c \
	|| fatal "Can't generate source from graph $st.graph"
    compile_c ${st}f.c
    compile_c ${st}m.c
    link $st ${st}f.o ${st}m.o
    run $st
    run_gcov ${st}f.c
    run_tggcov ${st}f.c
    compare_lines ${st}f.c
    vdo $top_builddir/${_DUP}src/tggcov -G ${st}f.c
done

