#!/usr/bin/env bash

. ../common.sh

init

compile_c foo.c
link foo foo.o

vncdo ./foo 1
vncdo ./foo 2
vncdo ./foo 3
vncdo ./foo 4

run_gcov foo.c
run_tggcov foo.c
compare_lines foo.c

# run_gcov bar.c
# run_tggcov bar.c
# compare_lines bar.c

