#!/usr/bin/env bash

. ../common.sh

init "suppression of lines by ifdef"

CDEFINES="-DFOO -DQUUX"

compile_c foo.c
link foo foo.o

run foo 1
run foo 2
run foo 23 423

tggcov_annotate_format new

subtest 1
tggcov_flags
run_tggcov foo.c
compare_file foo.c

subtest 2
tggcov_flags "-X FOO"
run_tggcov foo.c
compare_file foo.c

