#!/usr/bin/env bash
#
# ggcov - A GTK frontend for exploring gcov coverage data
# Copyright (c) 2011 Greg Banks <gnb@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id: runtest,v 1.2 2010-05-09 05:37:15 gnb Exp $
#

. ../common.sh

init "re-reading counts after start"

run_rereadtest ()
{
    vcmd "run_rereadtest $*"

    if vcapdo $TMP1 $_VALGRIND $top_builddir/${_DUP}src/rereadtest ; then
	cat $TMP1
	pass
    else
	cat $TMP1
	fail "rereadtest failed"
    fi
}

compile_c foo.c
link foo foo.o

subtest 1
run foo 1
run_gcov foo.c

subtest 2
run foo 2
run foo 23 423
run_gcov foo.c

run_rereadtest

subtest 1
compare_lines foo.c
subtest 2
compare_lines foo.c

