#!/bin/sh

CC="gcc"
CWARNFLAGS="-Wall"
CCOVFLAGS="-g -fprofile-arcs -ftest-coverage"

set -x
/bin/rm -f *.bb *.bbg
$CC $CWARNFLAGS $CCOVFLAGS -c foo.c || exit 1
$CC $CCOVFLAGS -o foo foo.o || exit 1

/bin/rm -f *.da *.gcov

./foo 1 2
./foo 3 4

gcov -b -f foo.c
