#!/usr/bin/env bash

. ../common.sh

init "an entire .c file is never executed"

compile_c foo.c
compile_c bar.c
compile_c quux.c
link foo foo.o quux.o
link bar bar.o quux.o

run foo 1
run foo 2
run foo 23 423
# Note we never run bar
[ -f foo.da -o -f foo.gcda ] || fail "no counts file foo.gcda produced"
[ -f quux.da -o -f quux.gcda ] || fail "no counts file quux.gcda produced"
[ -f bar.da -o -f bar.gcda ] && fail "counts file quux.gcda produced unexpectedly"

run_gcov foo.c
run_tggcov foo.c
compare_counts foo.c

run_gcov quux.c
run_tggcov quux.c
compare_counts quux.c

run_gcov bar.c
run_tggcov bar.c
compare_counts bar.c
