/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GGCov: @FILE@");
gchar *s = N_("_Number");
gchar *s = N_("_Count");
gchar *s = N_("_Source");
gchar *s = N_("Co_lors");
gchar *s = N_("F_ilenames");
gchar *s = N_("dummy");
gchar *s = N_("F_unctions");
gchar *s = N_("dummy");
