/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GGCov: Source @FILE@");
gchar *s = N_("_Number");
gchar *s = N_("_Block");
gchar *s = N_("_Count");
gchar *s = N_("_Source");
gchar *s = N_("Co_lors");
gchar *s = N_("F_ilenames");
gchar *s = N_("dummy");
gchar *s = N_("F_unctions");
gchar *s = N_("dummy");
gchar *s = N_("dummy");
gchar *s = N_("_Help");
gchar *s = N_("GGCov: Summary @FILE@");
gchar *s = N_("dummy");
gchar *s = N_("_Help");
gchar *s = N_("Filename");
gchar *s = N_("Function");
gchar *s = N_("Range");
gchar *s = N_("to");
gchar *s = N_("Overall");
gchar *s = N_("View...");
gchar *s = N_("View...");
gchar *s = N_("View...");
gchar *s = N_("Branches taken:");
gchar *s = N_("Branches executed:");
gchar *s = N_("Functions called:");
gchar *s = N_("Source lines executed:");
gchar *s = N_("GGCov: Function List");
gchar *s = N_("_Lines");
gchar *s = N_("_Calls");
gchar *s = N_("_Branches");
gchar *s = N_("_Percentages");
gchar *s = N_("dummy");
gchar *s = N_("_Help");
gchar *s = N_("Lines");
gchar *s = N_("Calls");
gchar *s = N_("Branches");
gchar *s = N_("Function\t");
gchar *s = N_("GGCov: File List");
gchar *s = N_("_Lines");
gchar *s = N_("_Calls");
gchar *s = N_("_Branches");
gchar *s = N_("_Percentages");
gchar *s = N_("dummy");
gchar *s = N_("_Help");
gchar *s = N_("Lines");
gchar *s = N_("Calls");
gchar *s = N_("Branches");
gchar *s = N_("File");
gchar *s = N_("GGCov: Calls @FILE@");
gchar *s = N_("dummy");
gchar *s = N_("_Help");
gchar *s = N_("From Function:");
gchar *s = N_("View...");
gchar *s = N_("To Function:");
gchar *s = N_("View...");
gchar *s = N_("Call From");
gchar *s = N_("Call To");
gchar *s = N_("Line");
gchar *s = N_("Arc");
gchar *s = N_("Count");
gchar *s = N_("GGCov: Call Graph @FILE@");
gchar *s = N_("dummy");
gchar *s = N_("_Help");
gchar *s = N_("Function:");
gchar *s = N_("View...");
gchar *s = N_("Distribution to Ancestors");
gchar *s = N_("Count");
gchar *s = N_("Function");
gchar *s = N_("Distribution to Descendants");
gchar *s = N_("Count");
gchar *s = N_("Function");
gchar *s = N_("GGCov: About @VERSION@");
gchar *s = N_("GGCov @VERSION@\n"
              "\n"
              "@AUTHOR@\n"
              "\n"
              "A program for browsing test coverage data for \n"
              "C programs built with the GNU C Compiler.\n"
              "\n"
              "@WARRANTY@");
gchar *s = N_("Licence...");
gchar *s = N_("GGCov: Licence");
gchar *s = N_("GGCov: Call Graph2");
gchar *s = N_("Zoom _In");
gchar *s = N_("Zoom _Out");
gchar *s = N_("Show _All");
gchar *s = N_("_Windows");
gchar *s = N_("dummy");
gchar *s = N_("_Help");
