#!/usr/bin/env bash
#
# ggcov - A GTK frontend for exploring gcov coverage data
# Copyright (c) 2006 Greg Banks <gnb@alphalink.com.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id: runtest,v 1.2 2010-05-09 03:00:46 gnb Exp $
#

. ../common.sh

init "unit test for class php_serializer"

if vcapdo $TMP1 $top_builddir/src/phptest ; then
    cat $TMP1
    pass
else
    fail "phpttest $args"
fi

if vdo diff -u $TMP1 phptest.expected ; then pass ; else fail "expected output differs" ; fi
